### ISSUE TITLE
Economy reward not working

### ISSUE THREAD

**Issue by ProsperCraft** [pie-flavor/React#2]
Is the plugin properly set up to hook into the sponge economy?

We have Economy lite and the other economy plugins are working perfectly.

Here is my config.

https://gist.github.com/ProsperCraft/61bdab052a40653e1f520253448d051c

**Comment by pie-flavor** [comment]
That's not the entire config; it has an unclosed brace and is missing `version` and `words[]`.
Also, what is your Sponge build, Minecraft version, and Forge build (if applicable)?

**Comment by ProsperCraft** [comment]
```
Minecraft: 1.10.2
SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
SpongeForge: 1.10.2-2123-6.0.0-BETA-1877
Minecraft Forge: 12.18.2.2123
```

Complete config-
https://gist.github.com/ProsperCraft/73e3c0d730cf26d90d6e99e694c7d446

**Comment by pie-flavor** [comment]
Logs? They're helpful. The only thing I can think of is that your currency isn't named `creds`.

**Comment by ProsperCraft** [comment]
[logs.zip](https://github.com/pie-flavor/React/files/604774/logs.zip)

It should not matter what my currency is called, Sponge has an economy api if you hook into that it should work right?

**Comment by pie-flavor** [comment]
Yes, it does matter. Sponge's economy API allows for multiple currencies, so the name is important. Like the plugin page says, don't include the `currency` line to use the default currency.

**Comment by ProsperCraft** [comment]
Thank you, we just set it up with a command.
