### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AdnanMia** [pie-flavor/React#3]
Would you be able to add a command, that runs the chat game? 

It would also be nice if everyone on the server got a notification saying so and so has won the game, and to be able to adjust the message the winner receives.

**Comment by pie-flavor** [comment]
What is the purpose of the command if it is already on interval? Admins shouldn't have to go to the trouble of activating it every five minutes. And you can set the messages via `rewards.commands[]` - just use tellraw.
