### ISSUE TITLE
Scheduler error

### ISSUE THREAD

**Issue by vectrixdevelops** [pie-flavor/React#4]
Here is a scheduler error I am receiving.

https://gist.github.com/connorhartley/a041d4d1c44dcae3cd2964d5ef19f913

**Comment by pie-flavor** [comment]
I must conclude that this is user error, somehow; the error is apparently claiming that List.size() is negative. Could you post a gist to your config?

**Comment by vectrixdevelops** [comment]
It's a newly generated config.

**Comment by pie-flavor** [comment]
Sponge build number?

**Comment by vectrixdevelops** [comment]
SpongeVanilla-1.11.2-6.0.0-BETA-192

**Comment by pie-flavor** [comment]
Well, there's your problem. This plugin was built for API 5; therefore it probably does not work on API 6.

**Comment by vectrixdevelops** [comment]
Well it was working on that build before... Not sure what has changed. The chat formatting for it also shows as raw json.

**Comment by pie-flavor** [comment]
That would be because

> This plugin was built for API 5; therefore it probably does not work on API 6.

**Comment by pie-flavor** [comment]
A plugin, I forget whose, was overriding the Sponge text serializer.
